REFERENCE_NUMBER_RANGE = [3, 4, 5, 6, 7]
TRIALS_NUMBER_RANGE = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
NUMBER_OF_LOOPS_INSIDE_TRIAL = 3
NUMBER_OF_TRIALS = 1

INFO_SHOW_TIME = 5
REFERENCE_SHOW_TIME = 2
FEEDBACK_SHOW_TIME = 1

# must be True or False
SOUND_USED = False
SOUND_FILE = "sound/test-music.wav"

FEEDBACK_BOX_BASE_COLOR = "gray"
BACKGROUND_COLOR = "black"