REFERENCE_NUMBER_RANGE = [3, 4, 5, 6, 7]
TRIALS_NUMBER_RANGE = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
NUMBER_OF_TRIAL_LOOPS = 3
NUMBER_OF_TRIALS = 2

REFERENCE_SHOW_TIME = 2
FEEDBACK_SHOW_TIME = 1

SOUND_FILE = "etc/kradgnikcuf-iileminatium-135247.wav"

FEEDBACK_BOX_BASE_COLOR = "gray"
BACKGROUND_COLOR = "black"